import { z } from 'zod';

import {
  messagePartDeltaEventSchema,
  messagePartRemovedEventSchema,
  messagePartSchema,
  messagePartTextSchema,
  messagePartToolSchema,
  messagePartToolStateSchema,
  messagePartUpdatedEventSchema,
  messageUpdatedEventSchema,
  opencodeProviderEventSchema,
  permissionAskedEventSchema,
  permissionUpdatedEventSchema,
  questionAskedEventSchema,
  questionAskedItemSchema,
  questionAskedOptionSchema,
  questionAskedToolRefSchema,
  sessionErrorEventSchema,
  sessionIdleEventSchema,
  sessionStatusEventSchema,
  sessionUpdatedEventSchema,
  type MessagePartDeltaEvent,
  type MessagePartRemovedEvent,
  type MessagePartText,
  type MessagePartTool,
  type MessagePartToolState,
  type MessagePartUpdatedEvent,
  type MessagePart,
  type MessageUpdatedEvent,
  type MessageUpdatedInfo,
  type MessageUpdatedModel,
  type MessageUpdatedSummaryDiff,
  type MessageUpdatedSummary,
  type MessageUpdatedTime,
  type OpencodeProviderEvent,
  type PermissionAskedEvent,
  type PermissionUpdatedEvent,
  type QuestionAskedEvent,
  type QuestionAskedItem,
  type QuestionAskedOption,
  type QuestionAskedToolRef,
  type SessionErrorEvent,
  type SessionIdleEvent,
  type SessionStatusEvent,
  type SessionUpdatedEvent,
} from './opencode-provider-event/index.ts';

/**
 * 当前态 `tool_event.event` payload family。
 * @remarks 现阶段只承接 `OpencodeProviderEvent`，不暴露 `SkillProviderEvent` 占位导出。
 */
export const gatewayToolEventPayloadSchema = opencodeProviderEventSchema;

export type GatewayToolEventPayload = z.output<typeof gatewayToolEventPayloadSchema>;

export {
  opencodeProviderEventSchema,
  messageUpdatedEventSchema,
  messagePartUpdatedEventSchema,
  messagePartDeltaEventSchema,
  messagePartRemovedEventSchema,
  sessionStatusEventSchema,
  sessionIdleEventSchema,
  sessionUpdatedEventSchema,
  sessionErrorEventSchema,
  permissionUpdatedEventSchema,
  permissionAskedEventSchema,
  questionAskedEventSchema,
  messagePartSchema,
  messagePartTextSchema,
  messagePartToolSchema,
  messagePartToolStateSchema,
  questionAskedOptionSchema,
  questionAskedItemSchema,
  questionAskedToolRefSchema,
};

export type {
  OpencodeProviderEvent,
  MessageUpdatedEvent,
  MessageUpdatedInfo,
  MessageUpdatedModel,
  MessageUpdatedSummaryDiff,
  MessageUpdatedSummary,
  MessageUpdatedTime,
  MessagePartText,
  MessagePartToolState,
  MessagePartTool,
  MessagePartUpdatedEvent,
  MessagePartDeltaEvent,
  MessagePartRemovedEvent,
  MessagePart,
  SessionStatusEvent,
  SessionIdleEvent,
  SessionUpdatedEvent,
  SessionErrorEvent,
  PermissionUpdatedEvent,
  PermissionAskedEvent,
  QuestionAskedOption,
  QuestionAskedItem,
  QuestionAskedToolRef,
  QuestionAskedEvent,
};
