import type { DownstreamScenario } from '@agent-plugin/bridge-runtime-sdk-lab-shared';

export function getDownstreamScenarios(): DownstreamScenario[] {
  return [
    {
      id: 'status-query-success',
      group: 'Status',
      title: 'status_query 正常',
      description: '下行 status_query 触发 Provider health，并上行 status_response。',
      raw: { type: 'status_query' },
      expected: { outcome: 'status_response', stage: 'success' },
    },
    {
      id: 'create-session-success',
      group: 'Create Session',
      title: 'create_session 正常',
      description: '创建会话成功后上行 session_created。',
      raw: {
        type: 'invoke',
        action: 'create_session',
        welinkSessionId: 'wl-lab-create',
        payload: { title: 'Lab Session', assistantId: 'assistant-lab' },
      },
      expected: { outcome: 'session_created', stage: 'success' },
    },
    {
      id: 'create-session-missing-welink',
      group: 'Create Session',
      title: 'create_session 缺少 welinkSessionId',
      description: '下行 payload 不符合 create_session 契约，且缺少可回包 welinkSessionId 时只记录 failure。',
      raw: {
        type: 'invoke',
        action: 'create_session',
        payload: { title: 'Missing welink' },
      },
      expected: { outcome: 'failure_only', stage: 'inbound_validation', errorIncludes: 'gateway_invalid_invoke' },
    },
    {
      id: 'create-session-provider-throws',
      group: 'Create Session',
      title: 'create_session Provider 抛错',
      description: '合法下行进入 usecase，Provider createSession 抛错后上行 tool_error。',
      raw: {
        type: 'invoke',
        action: 'create_session',
        welinkSessionId: 'wl-lab-create-error',
        payload: { title: 'Provider throws' },
      },
      expected: {
        outcome: 'tool_error',
        stage: 'provider_call',
        errorIncludes: 'SDK lab configured createSession failure',
        providerScenario: { command: 'createSession', kind: 'throw' },
      },
    },
    {
      id: 'chat-success',
      group: 'Chat',
      title: 'chat 正常',
      description: 'chat 下行触发 runMessage，并上行 tool_event / tool_done。',
      raw: {
        type: 'invoke',
        action: 'chat',
        welinkSessionId: 'wl-lab-chat',
        payload: { toolSessionId: 'tool-lab-chat', text: 'hello from downstream lab' },
      },
      expected: { outcome: 'tool_done', stage: 'success' },
    },
    {
      id: 'invalid-chat-missing-text',
      group: 'Chat',
      title: 'chat 缺少 text',
      description: '非法 chat payload 应由 inbound policy fail-closed 并上行 gateway_invalid_invoke tool_error。',
      raw: {
        type: 'invoke',
        messageId: 'gw-invalid-chat-missing-text',
        action: 'chat',
        welinkSessionId: 'wl-invalid-chat',
        payload: { toolSessionId: 'tool-invalid-chat' },
      },
      expected: { outcome: 'tool_error', stage: 'inbound_validation', errorIncludes: 'gateway_invalid_invoke' },
    },
    {
      id: 'invalid-chat-empty-text',
      group: 'Chat',
      title: 'chat text 为空',
      description: '空字符串 text 不满足 requiredTrimmedString，应产生 tool_error。',
      raw: {
        type: 'invoke',
        messageId: 'gw-invalid-chat-empty-text',
        action: 'chat',
        welinkSessionId: 'wl-invalid-chat-empty',
        payload: { toolSessionId: 'tool-invalid-chat-empty', text: '   ' },
      },
      expected: { outcome: 'tool_error', stage: 'inbound_validation', errorIncludes: 'gateway_invalid_invoke' },
    },
    {
      id: 'chat-provider-throws',
      group: 'Chat',
      title: 'chat Provider 抛错',
      description: '合法 chat 进入 runMessage，Provider 抛错后上行 tool_error。',
      raw: {
        type: 'invoke',
        action: 'chat',
        welinkSessionId: 'wl-chat-provider-error',
        payload: { toolSessionId: 'tool-chat-provider-error', text: 'boom' },
      },
      expected: {
        outcome: 'tool_error',
        stage: 'provider_call',
        errorIncludes: 'SDK lab configured runMessage failure',
        providerScenario: { command: 'runMessage', kind: 'throw' },
      },
    },
    {
      id: 'question-reply-pending-missing',
      group: 'Question',
      title: 'question_reply pending 不存在',
      description: '合法 question_reply 进入 usecase，但 pending question 不存在时上行交互失效 tool_error。',
      raw: {
        type: 'invoke',
        action: 'question_reply',
        welinkSessionId: 'wl-question-missing',
        payload: { questionId: 'question-missing', answers: [['yes']] },
      },
      expected: { outcome: 'tool_error', stage: 'interaction_resolution', errorIncludes: '当前交互已失效' },
    },
    {
      id: 'invalid-question-reply-answers',
      group: 'Question',
      title: 'question_reply answers 非 string[][]',
      description: 'answers 结构非法，应在下行校验阶段产生 tool_error。',
      raw: {
        type: 'invoke',
        action: 'question_reply',
        welinkSessionId: 'wl-invalid-question',
        payload: { questionId: 'question-invalid', answers: ['yes'] },
      },
      expected: { outcome: 'tool_error', stage: 'inbound_validation', errorIncludes: 'gateway_invalid_invoke' },
    },
    {
      id: 'permission-reply-pending-missing',
      group: 'Permission',
      title: 'permission_reply pending 不存在',
      description: '合法 permission_reply 进入 usecase，但 pending permission 不存在时上行交互失效 tool_error。',
      raw: {
        type: 'invoke',
        action: 'permission_reply',
        welinkSessionId: 'wl-permission-missing',
        payload: { permissionId: 'permission-missing', response: 'once' },
      },
      expected: { outcome: 'tool_error', stage: 'interaction_resolution', errorIncludes: '当前交互已失效' },
    },
    {
      id: 'invalid-permission-response',
      group: 'Permission',
      title: 'permission_reply response 非法',
      description: 'response 不在 once/always/reject 内，应产生 tool_error。',
      raw: {
        type: 'invoke',
        action: 'permission_reply',
        welinkSessionId: 'wl-invalid-permission',
        payload: { permissionId: 'permission-invalid', response: 'approve' },
      },
      expected: { outcome: 'tool_error', stage: 'inbound_validation', errorIncludes: 'gateway_invalid_invoke' },
    },
    {
      id: 'close-session-missing-tool-session',
      group: 'Close',
      title: 'close_session 缺少 toolSessionId',
      description: 'close_session payload 缺少 toolSessionId，应产生 tool_error。',
      raw: {
        type: 'invoke',
        action: 'close_session',
        welinkSessionId: 'wl-invalid-close',
        payload: {},
      },
      expected: { outcome: 'tool_error', stage: 'inbound_validation', errorIncludes: 'gateway_invalid_invoke' },
    },
    {
      id: 'abort-session-missing-tool-session',
      group: 'Abort',
      title: 'abort_session 缺少 toolSessionId',
      description: 'abort_session payload 缺少 toolSessionId，应产生 tool_error。',
      raw: {
        type: 'invoke',
        action: 'abort_session',
        welinkSessionId: 'wl-invalid-abort',
        payload: {},
      },
      expected: { outcome: 'tool_error', stage: 'inbound_validation', errorIncludes: 'gateway_invalid_invoke' },
    },
    {
      id: 'slash-commands-provider-throws',
      group: 'Slash',
      title: 'query_slash_commands Provider 抛错',
      description: '该 usecase 降级为空 slash_commands_result，不产生 tool_error。',
      raw: {
        type: 'invoke',
        action: 'query_slash_commands',
        toolSessionId: 'tool-slash-provider-error',
        traceId: 'trace-slash-provider-error',
        payload: {},
      },
      expected: {
        outcome: 'slash_commands_result',
        stage: 'provider_call',
        providerScenario: { command: 'listSlashCommands', kind: 'throw' },
      },
    },
    {
      id: 'invalid-slash-missing-trace',
      group: 'Slash',
      title: 'query_slash_commands 缺少 traceId',
      description: 'query_slash_commands 缺少 traceId，应产生 tool_error。',
      raw: {
        type: 'invoke',
        action: 'query_slash_commands',
        toolSessionId: 'tool-invalid-slash',
        payload: {},
      },
      expected: { outcome: 'tool_error', stage: 'inbound_validation', errorIncludes: 'gateway_invalid_invoke' },
    },
    {
      id: 'invalid-ext-parameters',
      group: 'Ext',
      title: 'extParameters.platformExtParam 非 JSON object',
      description: 'platformExtParam 为数组时应被下行契约拒绝并产生 tool_error。',
      raw: {
        type: 'invoke',
        action: 'chat',
        welinkSessionId: 'wl-invalid-ext',
        payload: {
          toolSessionId: 'tool-invalid-ext',
          text: 'hello',
          extParameters: { platformExtParam: [] },
        },
      },
      expected: { outcome: 'tool_error', stage: 'inbound_validation', errorIncludes: 'gateway_invalid_invoke' },
    },
    {
      id: 'invalid-invoke-no-route-target',
      group: 'Routing',
      title: '非法 invoke 无路由目标',
      description: '没有 welinkSessionId/toolSessionId 时，SDK 无法构造可路由 tool_error，只记录 failure。',
      raw: {
        type: 'invoke',
        action: 'chat',
        payload: { text: 'missing toolSessionId and welinkSessionId' },
      },
      expected: { outcome: 'failure_only', stage: 'inbound_validation', errorIncludes: 'gateway_invalid_invoke' },
    },
  ];
}
