import type { DownstreamScenario } from '@agent-plugin/bridge-runtime-sdk-lab-shared';

export function getDownstreamScenarios(): DownstreamScenario[] {
  return [
    {
      id: 'status-query-success',
      group: 'Status',
      title: 'status_query 正常',
      description: '下行 status_query 触发 Provider health，并上行 status_response。',
      raw: { type: 'status_query' },
      expected: { outcome: 'status_response', stage: 'success' },
    },
    {
      id: 'create-session-success',
      group: 'Create Session',
      title: 'create_session 正常',
      description: '创建会话成功后上行 session_created。',
      raw: {
        type: 'invoke',
        action: 'create_session',
        welinkSessionId: 'wl-lab-create',
        payload: { title: 'Lab Session', assistantId: 'assistant-lab' },
      },
      expected: { outcome: 'session_created', stage: 'success' },
    },
    {
      id: 'create-session-missing-welink',
      group: 'Create Session',
      title: 'create_session 缺少 welinkSessionId',
      description: '下行 payload 不符合 create_session 契约，且缺少可回包 welinkSessionId 时只记录 failure。',
      raw: {
        type: 'invoke',
        action: 'create_session',
        payload: { title: 'Missing welink' },
      },
      expected: { outcome: 'failure_only', stage: 'inbound_invalid' },
    },
    {
      id: 'create-session-provider-throws',
      group: 'Create Session',
      title: 'create_session Provider 抛错',
      description: '合法下行进入 usecase，Provider createSession 抛错后上行 tool_error。',
      raw: {
        type: 'invoke',
        action: 'create_session',
        welinkSessionId: 'wl-lab-create-error',
        payload: { title: 'Provider throws' },
      },
      expected: {
        outcome: 'tool_error',
        stage: 'command_failure',
        errorIncludes: 'SDK lab configured createSession failure',
        providerScenario: { command: 'createSession', kind: 'throw' },
      },
    },
    {
      id: 'chat-success',
      group: 'Chat',
      title: 'chat 正常',
      description: 'chat 下行触发 runMessage，并上行 tool_event / tool_done。',
      raw: {
        type: 'invoke',
        action: 'chat',
        welinkSessionId: 'wl-lab-chat',
        payload: { toolSessionId: 'tool-lab-chat', text: 'hello from downstream lab' },
      },
      expected: { outcome: 'tool_done', stage: 'success' },
    },
    {
      id: 'unsupported-invoke-action',
      group: 'Command Failure',
      title: 'unsupported invoke action',
      description: 'gateway 下行未知 invoke action，应在 command_failure 阶段上行不支持操作 tool_error。',
      raw: {
        type: 'invoke',
        action: 'rename_session',
        welinkSessionId: 'wl-unsupported-action',
        payload: { toolSessionId: 'tool-unsupported-action', title: 'new title' },
      },
      expected: { outcome: 'tool_error', stage: 'command_failure', errorIncludes: '暂不支持' },
    },
    {
      id: 'invalid-chat-missing-text',
      group: 'Chat',
      title: 'chat 缺少 text',
      description: '非法 chat payload 应由 inbound policy fail-closed，并上行请求格式异常 tool_error。',
      raw: {
        type: 'invoke',
        messageId: 'gw-invalid-chat-missing-text',
        action: 'chat',
        welinkSessionId: 'wl-invalid-chat',
        payload: { toolSessionId: 'tool-invalid-chat' },
      },
      expected: { outcome: 'tool_error', stage: 'inbound_invalid', errorIncludes: '请求格式异常，请稍后重试' },
    },
    {
      id: 'invalid-chat-empty-text',
      group: 'Chat',
      title: 'chat text 为空',
      description: '空字符串 text 不满足 requiredTrimmedString，应产生 tool_error。',
      raw: {
        type: 'invoke',
        messageId: 'gw-invalid-chat-empty-text',
        action: 'chat',
        welinkSessionId: 'wl-invalid-chat-empty',
        payload: { toolSessionId: 'tool-invalid-chat-empty', text: '   ' },
      },
      expected: { outcome: 'tool_error', stage: 'inbound_invalid', errorIncludes: '请求格式异常，请稍后重试' },
    },
    {
      id: 'chat-provider-throws',
      group: 'Chat',
      title: 'chat Provider 抛错',
      description: '合法 chat 进入 runMessage，Provider 抛错后上行 tool_error。',
      raw: {
        type: 'invoke',
        action: 'chat',
        welinkSessionId: 'wl-chat-provider-error',
        payload: { toolSessionId: 'tool-chat-provider-error', text: 'boom' },
      },
      expected: {
        outcome: 'tool_error',
        stage: 'command_failure',
        errorIncludes: 'SDK lab configured runMessage failure',
        providerScenario: { command: 'runMessage', kind: 'throw' },
      },
    },
    {
      id: 'chat-invalid-facts',
      group: 'Request Lifecycle',
      title: 'chat facts 顺序非法',
      description: 'runMessage 返回 ProviderRun，但 facts 未先 message.start 就 text.delta，应在 request_lifecycle 上行 request_run_failed tool_error。',
      raw: {
        type: 'invoke',
        action: 'chat',
        welinkSessionId: 'wl-chat-invalid-facts',
        payload: { toolSessionId: 'tool-chat-invalid-facts', text: 'invalid facts' },
      },
      expected: {
        outcome: 'tool_error',
        stage: 'request_lifecycle',
        errorIncludes: '当前请求处理失败',
        providerScenario: { command: 'runMessage', kind: 'invalid_fact' },
      },
    },
    {
      id: 'chat-enrich-failure-continues',
      group: 'Request Lifecycle',
      title: 'chat enrich failure 继续',
      description: 'facts 输出孤立 permission.reply，按方案只记录 diagnostics 并继续，不新增 tool_error。',
      raw: {
        type: 'invoke',
        action: 'chat',
        welinkSessionId: 'wl-chat-enrich',
        payload: { toolSessionId: 'tool-chat-enrich', text: 'enrich failure' },
      },
      expected: {
        outcome: 'diagnostics_only',
        stage: 'diagnostics_only',
        providerScenario: { command: 'runMessage', kind: 'enrich_failure' },
      },
    },
    {
      id: 'chat-terminal-failed',
      group: 'Request Terminal',
      title: 'chat terminal failed',
      description: 'ProviderRun.result 返回 failed，应在 request_terminal 上行 tool_error。',
      raw: {
        type: 'invoke',
        action: 'chat',
        welinkSessionId: 'wl-chat-terminal-failed',
        payload: { toolSessionId: 'tool-chat-terminal-failed', text: 'failed terminal' },
      },
      expected: {
        outcome: 'tool_error',
        stage: 'request_terminal',
        errorIncludes: 'SDK lab configured failed run',
        providerScenario: { command: 'runMessage', kind: 'failed_run' },
      },
    },
    {
      id: 'chat-terminal-session-not-found',
      group: 'Request Terminal',
      title: 'chat terminal session_not_found',
      description: 'ProviderRun.result 返回 session_not_found failed terminal，应上行带 reason 的 tool_error。',
      raw: {
        type: 'invoke',
        action: 'chat',
        welinkSessionId: 'wl-chat-session-missing',
        payload: { toolSessionId: 'tool-chat-session-missing', text: 'missing session' },
      },
      expected: {
        outcome: 'tool_error',
        stage: 'request_terminal',
        errorIncludes: 'SDK lab configured missing session',
        reason: 'session_not_found',
        providerScenario: { command: 'runMessage', kind: 'session_not_found' },
      },
    },
    {
      id: 'chat-result-reject',
      group: 'Command Failure',
      title: 'ProviderRun.result reject',
      description: 'ProviderRun.result 直接 reject，外层 command_failure catch 应收口为 tool_error。',
      raw: {
        type: 'invoke',
        action: 'chat',
        welinkSessionId: 'wl-chat-result-reject',
        payload: { toolSessionId: 'tool-chat-result-reject', text: 'result rejects' },
      },
      expected: {
        outcome: 'tool_error',
        stage: 'command_failure',
        errorIncludes: 'SDK lab configured ProviderRun.result rejection',
        providerScenario: { command: 'runMessage', kind: 'result_reject' },
      },
    },
    {
      id: 'question-reply-pending-missing',
      group: 'Question',
      title: 'question_reply pending 不存在',
      description: '合法 question_reply 进入 usecase，但 pending question 不存在时上行交互失效 tool_error。',
      raw: {
        type: 'invoke',
        action: 'question_reply',
        welinkSessionId: 'wl-question-missing',
        payload: { questionId: 'question-missing', answers: [['yes']] },
      },
      expected: { outcome: 'tool_error', stage: 'command_failure', errorIncludes: '当前交互已失效' },
    },
    {
      id: 'question-reply-provider-throws',
      group: 'Question',
      title: 'question_reply Provider 抛错',
      description: '先注册 pending question，再让 Provider replyQuestion 抛错，应在 command_failure 上行 tool_error。',
      raw: { trigger: 'multi_step', scenario: 'question-reply-provider-throws' },
      steps: [
        { kind: 'provider_scenario', scenario: { command: 'runMessage', kind: 'question_conflict' } },
        {
          kind: 'gateway_downstream',
          raw: {
            type: 'invoke',
            action: 'chat',
            welinkSessionId: 'wl-question-provider-throw',
            payload: { toolSessionId: 'tool-question-provider-throw', text: 'ask fixed question' },
          },
        },
        { kind: 'wait_for_uplink', timeoutMs: 1200 },
        { kind: 'provider_scenario', scenario: { command: 'replyQuestion', kind: 'throw' } },
        {
          kind: 'gateway_downstream',
          raw: {
            type: 'invoke',
            action: 'question_reply',
            welinkSessionId: 'wl-question-provider-throw',
            payload: { questionId: 'question-conflict-fixed', answers: [['yes']] },
          },
        },
      ],
      expected: {
        outcome: 'tool_error',
        stage: 'command_failure',
        errorIncludes: 'SDK lab configured replyQuestion failure',
      },
    },
    {
      id: 'question-pending-interaction-conflict',
      group: 'Request Lifecycle',
      title: 'question pending interaction 冲突',
      description: '两个不同 toolSessionId 注册相同 questionId，应在 request_lifecycle 上行 tool_error。',
      raw: { trigger: 'multi_step', scenario: 'question-pending-interaction-conflict' },
      steps: [
        { kind: 'provider_scenario', scenario: { command: 'runMessage', kind: 'question_conflict' } },
        {
          kind: 'gateway_downstream',
          raw: {
            type: 'invoke',
            action: 'chat',
            welinkSessionId: 'wl-question-conflict-a',
            payload: { toolSessionId: 'tool-question-conflict-a', text: 'first fixed question' },
          },
        },
        { kind: 'wait_for_uplink', timeoutMs: 1200 },
        {
          kind: 'gateway_downstream',
          raw: {
            type: 'invoke',
            action: 'chat',
            welinkSessionId: 'wl-question-conflict-b',
            payload: { toolSessionId: 'tool-question-conflict-b', text: 'second fixed question' },
          },
        },
      ],
      expected: {
        outcome: 'tool_error',
        stage: 'request_lifecycle',
        errorIncludes: '当前请求处理失败',
      },
    },
    {
      id: 'invalid-question-reply-answers',
      group: 'Question',
      title: 'question_reply answers 非 string[][]',
      description: 'answers 结构非法，应在下行校验阶段产生 tool_error。',
      raw: {
        type: 'invoke',
        action: 'question_reply',
        welinkSessionId: 'wl-invalid-question',
        payload: { questionId: 'question-invalid', answers: ['yes'] },
      },
      expected: { outcome: 'tool_error', stage: 'inbound_invalid', errorIncludes: '请求格式异常，请稍后重试' },
    },
    {
      id: 'permission-reply-pending-missing',
      group: 'Permission',
      title: 'permission_reply pending 不存在',
      description: '合法 permission_reply 进入 usecase，但 pending permission 不存在时上行交互失效 tool_error。',
      raw: {
        type: 'invoke',
        action: 'permission_reply',
        welinkSessionId: 'wl-permission-missing',
        payload: { permissionId: 'permission-missing', response: 'once' },
      },
      expected: { outcome: 'tool_error', stage: 'command_failure', errorIncludes: '当前交互已失效' },
    },
    {
      id: 'permission-reply-provider-throws',
      group: 'Permission',
      title: 'permission_reply Provider 抛错',
      description: '先注册 pending permission，再让 Provider replyPermission 抛错，应在 command_failure 上行 tool_error。',
      raw: { trigger: 'multi_step', scenario: 'permission-reply-provider-throws' },
      steps: [
        { kind: 'provider_scenario', scenario: { command: 'runMessage', kind: 'permission_conflict' } },
        {
          kind: 'gateway_downstream',
          raw: {
            type: 'invoke',
            action: 'chat',
            welinkSessionId: 'wl-permission-provider-throw',
            payload: { toolSessionId: 'tool-permission-provider-throw', text: 'ask fixed permission' },
          },
        },
        { kind: 'wait_for_uplink', timeoutMs: 1200 },
        { kind: 'provider_scenario', scenario: { command: 'replyPermission', kind: 'throw' } },
        {
          kind: 'gateway_downstream',
          raw: {
            type: 'invoke',
            action: 'permission_reply',
            welinkSessionId: 'wl-permission-provider-throw',
            payload: { permissionId: 'permission-conflict-fixed', response: 'once' },
          },
        },
      ],
      expected: {
        outcome: 'tool_error',
        stage: 'command_failure',
        errorIncludes: 'SDK lab configured replyPermission failure',
      },
    },
    {
      id: 'permission-pending-interaction-conflict',
      group: 'Request Lifecycle',
      title: 'permission pending interaction 冲突',
      description: '两个不同 toolSessionId 注册相同 permissionId，应在 request_lifecycle 上行 tool_error。',
      raw: { trigger: 'multi_step', scenario: 'permission-pending-interaction-conflict' },
      steps: [
        { kind: 'provider_scenario', scenario: { command: 'runMessage', kind: 'permission_conflict' } },
        {
          kind: 'gateway_downstream',
          raw: {
            type: 'invoke',
            action: 'chat',
            welinkSessionId: 'wl-permission-conflict-a',
            payload: { toolSessionId: 'tool-permission-conflict-a', text: 'first fixed permission' },
          },
        },
        { kind: 'wait_for_uplink', timeoutMs: 1200 },
        {
          kind: 'gateway_downstream',
          raw: {
            type: 'invoke',
            action: 'chat',
            welinkSessionId: 'wl-permission-conflict-b',
            payload: { toolSessionId: 'tool-permission-conflict-b', text: 'second fixed permission' },
          },
        },
      ],
      expected: {
        outcome: 'tool_error',
        stage: 'request_lifecycle',
        errorIncludes: '当前请求处理失败',
      },
    },
    {
      id: 'invalid-permission-response',
      group: 'Permission',
      title: 'permission_reply response 非法',
      description: 'response 不在 once/always/reject 内，应产生 tool_error。',
      raw: {
        type: 'invoke',
        action: 'permission_reply',
        welinkSessionId: 'wl-invalid-permission',
        payload: { permissionId: 'permission-invalid', response: 'approve' },
      },
      expected: { outcome: 'tool_error', stage: 'inbound_invalid', errorIncludes: '请求格式异常，请稍后重试' },
    },
    {
      id: 'close-session-missing-tool-session',
      group: 'Close',
      title: 'close_session 缺少 toolSessionId',
      description: 'close_session payload 缺少 toolSessionId，应产生 tool_error。',
      raw: {
        type: 'invoke',
        action: 'close_session',
        welinkSessionId: 'wl-invalid-close',
        payload: {},
      },
      expected: { outcome: 'tool_error', stage: 'inbound_invalid', errorIncludes: '请求格式异常，请稍后重试' },
    },
    {
      id: 'close-session-provider-throws',
      group: 'Close',
      title: 'close_session Provider 抛错',
      description: '合法 close_session 进入 usecase，Provider closeSession 抛错后上行 tool_error。',
      raw: {
        type: 'invoke',
        action: 'close_session',
        welinkSessionId: 'wl-close-provider-error',
        payload: { toolSessionId: 'tool-close-provider-error' },
      },
      expected: {
        outcome: 'tool_error',
        stage: 'command_failure',
        errorIncludes: 'SDK lab configured closeSession failure',
        providerScenario: { command: 'closeSession', kind: 'throw' },
      },
    },
    {
      id: 'abort-session-missing-tool-session',
      group: 'Abort',
      title: 'abort_session 缺少 toolSessionId',
      description: 'abort_session payload 缺少 toolSessionId，应产生 tool_error。',
      raw: {
        type: 'invoke',
        action: 'abort_session',
        welinkSessionId: 'wl-invalid-abort',
        payload: {},
      },
      expected: { outcome: 'tool_error', stage: 'inbound_invalid', errorIncludes: '请求格式异常，请稍后重试' },
    },
    {
      id: 'abort-session-provider-throws',
      group: 'Abort',
      title: 'abort_session Provider 抛错',
      description: '合法 abort_session 进入 usecase，Provider abortSession 抛错后上行 tool_error。',
      raw: {
        type: 'invoke',
        action: 'abort_session',
        welinkSessionId: 'wl-abort-provider-error',
        payload: { toolSessionId: 'tool-abort-provider-error' },
      },
      expected: {
        outcome: 'tool_error',
        stage: 'command_failure',
        errorIncludes: 'SDK lab configured abortSession failure',
        providerScenario: { command: 'abortSession', kind: 'throw' },
      },
    },
    {
      id: 'slash-commands-provider-throws',
      group: 'Slash',
      title: 'query_slash_commands Provider 抛错',
      description: '该 usecase 降级为空 slash_commands_result，不产生 tool_error。',
      raw: {
        type: 'invoke',
        action: 'query_slash_commands',
        toolSessionId: 'tool-slash-provider-error',
        traceId: 'trace-slash-provider-error',
        payload: {},
      },
      expected: {
        outcome: 'slash_commands_result',
        stage: 'success',
        providerScenario: { command: 'listSlashCommands', kind: 'throw' },
      },
    },
    {
      id: 'invalid-slash-missing-trace',
      group: 'Slash',
      title: 'query_slash_commands 缺少 traceId',
      description: 'query_slash_commands 缺少 traceId，应产生 tool_error。',
      raw: {
        type: 'invoke',
        action: 'query_slash_commands',
        toolSessionId: 'tool-invalid-slash',
        payload: {},
      },
      expected: { outcome: 'tool_error', stage: 'inbound_invalid', errorIncludes: '请求格式异常，请稍后重试' },
    },
    {
      id: 'invalid-ext-parameters',
      group: 'Ext',
      title: 'extParameters.platformExtParam 非 JSON object',
      description: 'platformExtParam 为数组时应被下行契约拒绝并产生 tool_error。',
      raw: {
        type: 'invoke',
        action: 'chat',
        welinkSessionId: 'wl-invalid-ext',
        payload: {
          toolSessionId: 'tool-invalid-ext',
          text: 'hello',
          extParameters: { platformExtParam: [] },
        },
      },
      expected: { outcome: 'tool_error', stage: 'inbound_invalid', errorIncludes: '请求格式异常，请稍后重试' },
    },
    {
      id: 'invalid-invoke-no-route-target',
      group: 'Routing',
      title: '非法 invoke 无路由目标',
      description: '没有 welinkSessionId/toolSessionId 时，SDK 无法构造可路由 tool_error，只记录 failure。',
      raw: {
        type: 'invoke',
        action: 'chat',
        payload: { text: 'missing toolSessionId and welinkSessionId' },
      },
      expected: { outcome: 'failure_only', stage: 'inbound_invalid' },
    },
    {
      id: 'outbound-run-invalid-facts',
      group: 'Outbound Terminal',
      title: 'emitOutboundRun facts 顺序非法',
      description: 'Provider 主动 outbound run 输出非法 facts，应在 outbound_terminal 上行 tool_error。',
      trigger: 'provider_outbound',
      raw: { trigger: 'provider_outbound', kind: 'invalid_fact' },
      expected: {
        outcome: 'tool_error',
        stage: 'outbound_terminal',
        errorIncludes: 'text.delta',
        providerScenario: { command: 'outbound', kind: 'invalid_fact' },
      },
    },
    {
      id: 'outbound-run-facts-throw',
      group: 'Outbound Terminal',
      title: 'emitOutboundRun facts iterator 抛错',
      description: 'Provider 主动 outbound run 的 async iterable 中途抛错，应在 outbound_terminal 上行 tool_error。',
      trigger: 'provider_outbound',
      raw: { trigger: 'provider_outbound', kind: 'facts_throw' },
      expected: {
        outcome: 'tool_error',
        stage: 'outbound_terminal',
        errorIncludes: 'SDK lab configured facts iterator failure',
        providerScenario: { command: 'outbound', kind: 'facts_throw' },
      },
    },
    {
      id: 'outbound-run-enrich-failure-continues',
      group: 'Outbound Terminal',
      title: 'emitOutboundRun enrich failure 继续',
      description: 'Provider 主动 outbound run 输出孤立 permission.reply，按方案只记录 diagnostics 并继续，不新增 tool_error。',
      trigger: 'provider_outbound',
      raw: { trigger: 'provider_outbound', kind: 'enrich_failure' },
      expected: {
        outcome: 'diagnostics_only',
        stage: 'diagnostics_only',
        providerScenario: { command: 'outbound', kind: 'enrich_failure' },
      },
    },
    {
      id: 'mock-gateway-disconnect',
      group: 'Fake Gateway',
      title: 'Mock gateway 主动断开',
      description: '模拟 gateway 运行中不可用；该场景不递归发送 tool_error，应通过 runtime status/diagnostics 感知。',
      trigger: 'mock_gateway_disconnect',
      raw: { trigger: 'mock_gateway_disconnect' },
      expected: { outcome: 'runtime_failed', stage: 'lifecycle_status' },
    },
  ];
}
